feat: launch support neutree api deploy (#35)
* chore: launch support api compose deploy

* remove chat playgroud implementation

---------

Co-authored-by: Levi080513 <weihuang@arcfra.com>

diff --git a/Dockerfile.api b/Dockerfile.api
--- a/Dockerfile.api
+++ b/Dockerfile.api
@@ -1,24 +1,38 @@
-# syntax=docker/dockerfile:1.4
-
-# Copyright 2022.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#     http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-
-# Build architecture
 ARG ARCH
 
-# Build the manager binary
-FROM golang:1.23 as builder
+# Clone the fronted code
+FROM alpine/git:v2.47.2 as fronted-code
+ARG UI_VERSION
+RUN git clone -b ${UI_VERSION} https://github.com/neutree-ai/ui.git
+
+# Build the fronted
+FROM node:22.13.1 as fronted-base
+
+WORKDIR /app/refine
+COPY --from=fronted-code /git/ui/ /app/refine/
+
+# Fetch the fronted dependencies
+FROM fronted-base as fronted-deps
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Build the fronted static files
+FROM fronted-base as fronted-builder
+
+ENV NODE_ENV production
+
+COPY --from=fronted-deps /app/refine/node_modules ./node_modules
+
+COPY . .
+
+RUN yarn build
+
+# Build the api binary
+FROM golang:1.23 as go-builder
 WORKDIR /workspace
 
 # Run this with docker build --build_arg $(go env GOPROXY) to override the goproxy
@@ -44,8 +58,15 @@ RUN CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} \
     -o neutree-api cmd/neutree-api/neutree-api.go
 
 FROM --platform=linux/${ARCH} ubuntu:22.04
+ENV NODE_ENV production
 
+# Copy api binary
 WORKDIR /
-COPY --from=builder /workspace/neutree-api .
+COPY --from=go-builder /workspace/neutree-api .
+
+# Copy the fronted static files
+RUN mkdir -p /public
+COPY --from=fronted-builder /app/refine/dist /public
+
 USER root
 ENTRYPOINT ["/neutree-api"]
